apiVersion: v1
kind: Deployment
metadata:
  name: las-app
spec:
  template:
    spec:
      containers:
      - name: las-app-container
        image: gcr.io/uptimebot/demo:v1.0.0
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 2
        ports:
          - containerPort: 8080
            name: http
