apiVersion: v1
kind: Deployment
metadata:
  name: las-app
spec:
  template:
    spec:
      containers:
      - name: las-app-container
        image: gcr.io/uptimebot/demo:v1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
