apiVersion: v1
kind: Pod
metadata:
  name: las-app-pod
spec:
  containers:
  - name: las-app-container
    image: gcr.io/uptimebot/demo:v1.0.0
    env:
    - name: TheMisteriousUnknownMansName
      valueFrom:
        secretKeyRef:
          name: las-secret
          key: username
    - name: TheVeryStr0ngPa$$word
      valueFrom:
        secretKeyRef:
          name: las-secret
          key: password
  restartPolicy: Never
