apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  volumes:
  - name: firstv
    emptyDir: {}
  containers:
  - name: 1st
    image: gcr.io/uptimebot/demo:v1.0.0
    volumeMounts:
    - name: version1
      mountPath: /usr/share/v1
  - name: 2nd
    image: gcr.io/uptimebot/demo:v2.0.0
    volumeMounts:
    - name: version2
      mountPath: /usr/share/v2